# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
unsetopt beep
setopt SHARE_HISTORY
bindkey -v
# enable command history search
bindkey "^[OA" history-beginning-search-backward
bindkey "^[OB" history-beginning-search-forward
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/theron/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# .zshrc
fpath+=$HOME/.zsh/pure
# export PATH="$HOME/.emacs.d/bin:$PATH"
export PATH="./node_modules/.bin:$PATH"
export EDITOR="nvim"

# nvm
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

if type globus > /dev/null 2>&1; then
    eval "$(globus --zsh-completer)"
fi

autoload -Uz promptinit
promptinit

prompt pure

alias vim="nvim ."

# git
alias ga="git add"
alias gb="git branch"
alias gbd="git branch -D"
alias gc="git commit"
alias gco="git checkout"
alias gd="git diff"
alias gf="git fetch --all --prune"
alias gl="git pull"
alias glo="git log --oneline"
alias gpt="git push theron"
alias gr="git rebase"
alias gst="git status"
alias gunwip='git log -n 1 | grep -q -c "\-\-wip\-\-" && git reset HEAD~1'
alias gwip='git add -A; git ls-files --deleted -z | xargs -r0 git rm; git commit -m "--wip--" --no-verify'

alias cat="batcat --theme=TwoDark"
alias ls="exa -la"
alias update="sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y && flatpak update -y && flatpak remove --unused -y"

# pnpm
export PNPM_HOME="/home/theron/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# Created by `pipx` on 2025-09-26 03:03:59
export PATH="$PATH:/home/theron/.local/bin"
